export const AnimationActionTypes = {

  //below is for CHARACTER
  SET_CHARACTER_POSITION_LEFT: "SET_CHARACTER_POSITION_LEFT",
  SET_CHARACTER_DIRECTION_ANIMATION: "SET_CHARACTER_DIRECTION_ANIMATION",
  END_CHARACTER_ANIMATION:"END_CHARACTER_ANIMATION",
  START_CHARACTER_ANIMATION:"START_CHARACTER_ANIMATION",
  START_CHAR_ANIM_COMP: "START_CHAR_ANIM_COMP",
  END_CHAR_ANIM_COMP:"END_CHAR_ANIM_COMP",
  SET_CHAR_POS_LEFT_COMP: "SET_CHAR_POS_LEFT_COMP",
  SET_CHAR_DIRECTION_COPM: "SET_CHAR_DIRECTION_COPM",
  
  // below is for SPEECH BUBBLE
  END_SPEECH_BUBBLE_ANIMATION: "EEND_SPEECH_BUBBLE_ANIMATION",
  START_SPEECH_BUBBLE_ANIMATION: "START_SPEECH_BUBBLE_ANIMATION",
  
}